# Generated by Django 4.1 on 2023-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название группы')),
                ('chat_id', models.BigIntegerField(verbose_name='ID группы')),
                ('sheet', models.URLField(help_text='Cсылка на открытый google sheet или demonstrationalemail@gmail.com имеет доступ к этому файлу', verbose_name='Google sheet url')),
            ],
            options={
                'verbose_name': 'Группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('api_key', models.BigIntegerField(verbose_name='App api_id')),
                ('api_hash', models.CharField(max_length=150, verbose_name='App api_hash')),
                ('phone', models.CharField(help_text='Phone with out +', max_length=25, verbose_name='Phone')),
                ('password', models.CharField(blank=True, default='517707', help_text='Пароль от двухэтапной аунтефикации', max_length=250, null=True)),
                ('is_active', models.BooleanField(default=False, editable=False, verbose_name='Активный ли аккаунт')),
            ],
            options={
                'verbose_name': 'Телеграм Аккаунт Пользователя',
                'verbose_name_plural': 'Телеграм Аккаунты Пользователей',
            },
        ),
    ]
